name: Update Keywords

on:
  repository_dispatch:
    types: [update-keywords]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Update keywords.txt
        env:
          KEYWORD: ${{ github.event.client_payload.keyword }}
        run: |
          test -n "$KEYWORD" || (echo "Ошибка: keyword пустой" && exit 1)
          echo "$KEYWORD" > keywords.txt

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add keywords.txt
          git diff --staged --quiet || git commit -m "Update keywords: ${{ github.event.client_payload.keyword }}"
          git pull --rebase origin main
          git push origin main
