name: Update Keywords

on:
  repository_dispatch:
    types: [update-keywords]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update keywords.txt
        run: echo "${{ github.event.client_payload.keyword }}" > keywords.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add keywords.txt
          git commit -m "Update keywords"
          git push
